// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU3vy6f_nU8FM8xAV9WuwYtH5NbTbsQ3E',
    appId: '1:532103208443:web:c25347f70058df2f9cbf5e',
    messagingSenderId: '532103208443',
    projectId: 'flutterlawyerapp',
    authDomain: 'flutterlawyerapp.firebaseapp.com',
    storageBucket: 'flutterlawyerapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1A4g2sWgFfY5q5zgTlMe3QOVRzGgGfJM',
    appId: '1:532103208443:android:e201dbdbc0f87f029cbf5e',
    messagingSenderId: '532103208443',
    projectId: 'flutterlawyerapp',
    storageBucket: 'flutterlawyerapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2SxPgYSx1GejsPx5rQdAEVvJ4K2EEOPc',
    appId: '1:532103208443:ios:3909e060aa63406d9cbf5e',
    messagingSenderId: '532103208443',
    projectId: 'flutterlawyerapp',
    storageBucket: 'flutterlawyerapp.appspot.com',
    iosBundleId: 'com.example.lawyerAppGoogleSolutions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2SxPgYSx1GejsPx5rQdAEVvJ4K2EEOPc',
    appId: '1:532103208443:ios:5d5e25d1bba711a89cbf5e',
    messagingSenderId: '532103208443',
    projectId: 'flutterlawyerapp',
    storageBucket: 'flutterlawyerapp.appspot.com',
    iosBundleId: 'com.example.lawyerAppGoogleSolutions.RunnerTests',
  );
}
